### ISSUE TITLE
V5.0 throwing error: "URI: file:/github/workspace is not valid in the workspace!"

### ISSUE THREAD

**Issue by ali-oatley** [xanderhendriks/action-build-stm32cubeide#10]
v5.0 throws this error: "URI: file:/github/workspace is not valid in the workspace!" and then skips the build

I tested with v10.0 and this error doesn't occur. Is it possible to apply a fix to v5.0?

**Comment by xanderhendriks** [comment]
@ali-oatley could you please let me know if your problem is resolved, so we can close this issue?

**Comment by ali-oatley** [comment]
We ended up using just the docker container and not the action since we had some custom needs, so I'll close this thanks.
