### ISSUE TITLE
Include path configurations

### ISSUE THREAD

**Issue by smartnexus** [xanderhendriks/action-build-stm32cubeide#11]
If I am locating some libraries code outside de default project path, is it possible to specify another directory as STMCubeIde allows?

**Comment by xanderhendriks** [comment]
I am not quite sure what you mean. If you have included files from other locations in the project, then as long as it builds on your local machine, the action will work.

**Comment by smartnexus** [comment]
The main point is that i reference files without including the hole path, for example I do 
`#include <core_mqtt.h>` and this file is not located on the build path, is on another folder outside the core, inc paths

**Comment by xanderhendriks** [comment]
That's fine. That's what most people will do. No one likes writing the whole include path for every include. That's what the include path configuration you showed is for.
All the configurations, inclusive the include paths, are saved in the project file and the build action will use them. You will only have to make sure your local directory structure is the same as when the action is building in the cloud.
Are all project files in the same repo in github? What is the actual error you are getting? It can't find core_mqtt.h? Add `find` in your pipeline, so you can see a listing of all files that are there.

**Comment by xanderhendriks** [comment]
Were you able to get this to work or are you still having problems?

**Comment by xanderhendriks** [comment]
I'll just assume you got it working and close the issue.

Always a bit disappointing when people are happy to take the time to report an issue they are having, but don't report back if the free help has resolved their problem.

**Comment by smartnexus** [comment]
> Were you able to get this to work or are you still having problems?

Working, it was my configurarion

**Comment by smartnexus** [comment]
working approach https://github.com/smartnexus/slope-monitoring-freertos

**Comment by smartnexus** [comment]
thanks for your help, it was my fault sorry :(

**Comment by xanderhendriks** [comment]
Good to hear you have got it working now. Thanks for the update.
