### ISSUE TITLE
Custom toolchain

### ISSUE THREAD

**Issue by erikvoh** [xanderhendriks/action-build-stm32cubeide#13]
Hi,
first of all thanks for making this project, it is really cool. 
I want to use custom toolchain (ex. STM32-9-2020-q2-update), but I can't get it working. I know it is possible to use gcc without stm32cubeide, but I don't want to create makefile for every change in project, which can be done in IDE settings. 
I was wondering if anyone could point me in right direction?

**Comment by xanderhendriks** [comment]
Did you look at underlying docker image [docker-stm32cubeide](https://github.com/xanderhendriks/docker-stm32cubeide)? If you for this one you should be able to add a different version of the compiler. If you configure it properly in the project file than I would assume a fork of the action-build could use this and run the custom toolchain for you.

**Comment by xanderhendriks** [comment]
Is this still an issue for you?

**Comment by xanderhendriks** [comment]
@erikvoh as you didn't come back to me, I assume you are no longer having a problem. So I'll close this issue.
