### ISSUE TITLE
Example Project?

### ISSUE THREAD

**Issue by Seth10001** [xanderhendriks/action-build-stm32cubeide#3]
Hi @xanderhendriks, first of all thank you for making this/sharing it.

Would you have an example STM32 project of this working?

We're having some trouble getting it to find our project: https://github.com/Solar-Gators/Sunrider-SteeringFirmware-2022/pull/1/checks

**Comment by xanderhendriks** [comment]
Hi Raymond,

No worries. My apologies for the delay, I was on a holiday. Looks like you already have it working now, is that correct?

Let me know if you are still having any issues.

I'm currently in the process of adding CppUTest to a project I'm working on. Once completed I'll create a sample project online as it will also serve as a good starting point for my own future projects.

Cheers,
Xander

**Comment by Seth10001** [comment]
No trouble, thanks for the reply! We ended up forking your repository and [creating our own](https://github.com/Solar-Gators/Sunrider-SteeringFirmware-2022/blob/2c69f42f71d0aea236190314c4509016c5160e20/.github/workflows/main.yml#L30-L33). The only thing we really changed is we pulled the IDE from STM's website and uploaded it to google drive. For some reason the STM IDE that's in this repo could not detect our project.

With that said, I'd love to see an example and maybe switch back to this more centualized repo.

**Comment by xanderhendriks** [comment]
There is now a [simple sample project](https://github.com/xanderhendriks/stm32-sample-application). Let me know what you think. Depending upon comments I might add some automated testing in the future.

I'm closing this issue now assuming that the PR I created in your project solved your problem.

**Comment by Seth10001** [comment]
Hey! This looks great, thank you for putting it together. We also have some example renode tests if you were interested.
https://github.com/Solar-Gators/Sunrider-TelemetryFirmware-2022/blob/2a0775161eebe8ae9f580df806f3e5581ab3a2b7/tests/telemetry.robot

**Comment by xanderhendriks** [comment]
Thanks for that. I had a look at the Renode website. Looks impressive.
