### ISSUE TITLE
Action not working with act

### ISSUE THREAD

**Issue by frankplow** [xanderhendriks/action-build-stm32cubeide#4]
When using [act](https://github.com/nektos/act), I get the following error:
```
/entrypoint.sh: line 3: stm32cubeide: command not found
/entrypoint.sh: line 4: headless-build.sh: command not found
```
The action works fine when run on GitHub, so I think this is due to some idiosyncrasy of act. The reason I am putting this issue here is because act is generally very well supported, including with Docker images. I wonder if there's something this action's Docker image is doing which is throwing it off?

Docker desktop shows two images with IDs 49cf70126577 and 95106a203c9d, both of which seem to have set up fine and installed STM32CubeIDE. Only 49cf70126577 seems to spin up when I run act.

Thanks for this action, it is very useful.

**Comment by xanderhendriks** [comment]
@frankplow I am not a act user myself, but I'm happy to help you fix the problem so it can benefit other people using this action with this tool.
When you mention these 2 ID's are these images created from different versions of the [action-build-stm32cubeide](https://github.com/xanderhendriks/action-build-stm32cubeide)? If so, which versions? In that case I can check if there is any obvious difference between the 2.
Alternatively you can create a fork of the repo and modify the entrypoint.sh and add some extra commands that might help identify why it can't find the stm tools.

**Comment by frankplow** [comment]
Looked into this a little more today. STM32CubeIDE is installed, however the `ENV PATH` layer in the Docker image does not work with act. There is [an issue](https://github.com/nektos/act/issues/896) already in the act repo. Workarounds include:
* Using absolute paths in entrypoint.sh
* Symlinking `/opt/st/stm32cubeide_1.10.1/stm32cubeide` and `/opt/st/stm32cubeide_1.10.1/headless-build.sh` into a path which is in the default PATH
* Adding `/opt/st/stm32cubeide_1.10.1/` to the default PATH when instantiating the action

There is [a related PR](https://github.com/nektos/act/pull/1503) in act master, however this didn't fix the problem for me.

**Comment by xanderhendriks** [comment]
Thanks for looking into this in more detail and posting a work around for as long as it hasn't been fixed in act. Hopefully it will save other people trying to use this action in act some time.
