### ISSUE TITLE
v1.13.1 is ready to update

### ISSUE THREAD

**Issue by Linjieqiang** [xanderhendriks/action-build-stm32cubeide#6]

**Comment by xanderhendriks** [comment]
Hi @Linjieqiang I created the Docker with the latest version. I'm not using the latest IDE myself yet. Are you able to test if it works?

**Comment by xanderhendriks** [comment]
Hmm. Did something go wrong? If you use the new v10.0 in your github action yaml file then it should pickup the docker with this [line](https://github.com/xanderhendriks/action-build-stm32cubeide/blob/master/Dockerfile#L2) from the [docker hub](https://hub.docker.com/r/xanderhendriks/stm32cubeide/tags)

**Comment by xanderhendriks** [comment]
I don't quite understand what I'm looking at here. You'll have to supply more information, like which command were you running and in which environment. It looks like Stm32CubeIde tried to open a project, but somehow it had an issue with it.
I just configured my sample application to use the new version of the github action and it works without any problems. Maybe you can have a look [here](https://github.com/xanderhendriks/stm32-sample-application/actions/runs/5937493372) to see what you are doing different.
