### ISSUE TITLE
Get Binary Output

### ISSUE THREAD

**Issue by kf1375** [xanderhendriks/action-build-stm32cubeide#7]
Hi @xanderhendriks. Thank you for sharing this helpful repo.

Can you explain how to get .elf output?

I want to release the binary output after a successful build.

**Comment by xanderhendriks** [comment]
Please have a look at my [sample application repo](https://github.com/xanderhendriks/stm32-sample-application) it shows how to release the binaries.

**Comment by kf1375** [comment]
Great. Thanks!
